### ISSUE TITLE
Pickups: Weapons

### ISSUE THREAD

**Issue by rijkvp** [djog/djog_unos_2021#11]
Create a pickup system that allows the player to pick up weapons spread around the level.

**Comment by antonhensen81** [comment]
@rijkvp We took over most of this issue. It's not perfect but it works! Code is on Max his branch. Let's check it next week

**Comment by rijkvp** [comment]
@antonhensen81 , nice but this was alreay done...

**Comment by rijkvp** [comment]
If you read the history, you can see I mentioned this issue in a commit: adfb93e40fca01bf25f39d258f44c3a65206239a.

**Comment by rijkvp** [comment]
Done!
